<?php include "../header.php";?>

	<section>
		<div class="text">
			<p style="text-align: justify;"><strong><a href="http://www.ted.com">TED</a></strong> es una organización sin fines de lucro dedicada a difundir ideas valiosas. Se inició en 1984 con una conferencia que reunió a personas de tres ámbitos: <strong>Tecnología, Entretenimiento, y Diseño</strong>. Desde entonces se ha ampliado a una diversa gama de temáticas de interés general y ha crecido para apoyar a aquellos que a través de sus ideas intentan cambiar el mundo por medio de distintas iniciativas. Su misión es la de divulgar y diseminar ideas.</p>
			<p style="text-align: justify;">Las conferencias anuales en Long Beach, Palm Springs, California, y Edimburgo, reúnen a los pensadores más fascinantes del mundo, que son desafiados a dar la mejor disertación de sus vidas en tan solo 18 minutos o menos. Por TED han pasado algunos oradores de la talla de: <strong>Bill Gates, Al Gore, Jane Goodall, Elizabeth Gilbert, Sir Richard Branson, Nandan Nilekani, Philippe Starck, Ngozi Okonjo-Iweala, Isabel Allende y el primer ministro británico, Gordon Brown</strong>. En TED.com se encuentran a disposición del público mundial y en forma gratuita, las mejores charlas y representaciones. Ya se puede acceder a unas 1000 TEDTalks y cada semana se suman más. Están todas subtituladas en inglés y muchas tienen traducciones a varios idiomas, hechas por voluntarios de alrededor del globo. Los videos son cedidos bajo licencia para ser compartidos.</p>
			<p style="text-align: justify;">TED ha establecido un premio anual por el que a individuos excepcionales con un deseo de cambiar el mundo se les da la oportunidad de empujar sus deseos a la acción. TEDx ofrece la posibilidad de que personas o grupos organicen un evento independiente en cualquier lugar del mundo. A su vez el programa TEDFellows ayuda a las personas innovadoras a ser parte de la comunidad TED y así amplificar el impacto de sus destacados proyectos y actividades. <strong>Cree apasionadamente en el poder de las ideas para cambiar actitudes, vidas y también el mundo.</strong> TED está construyendo una plataforma que ofrece conocimiento gratuito e inspiración de las mentes más extraordinarias del mundo, además de una comunidad de almas curiosas capaces de involucrarse con estas ideas y entre ellos mismo. Su sitio web, lanzado en abril de 2007, es un trabajo en progreso que no cesa de evolucionar en forma permanente. Hoy TED es considerada una comunidad global. Una comunidad que le da la bienvenida a personas de cualquier disciplina y cultura, interesadas en alcanzar un entendimiento más profundo del mundo en el que vivimos. Si tenés una buena idea, visitá <strong><a href="http://www.ted.com">www.ted.com</a></strong>, TED quiere saber de vos.</p>
		</div>
	</section>

<?php include "../footer.php";?>